function Offspring = GA(Parent,Parameter)
global encoding lower upper
%GA - Genetic operators for real, binary, and permutation based encodings.
%
%   Off = GA(P) returns the offsprings generated by genetic operators,
%   where P1 is a set of parents. If P is an array of INDIVIDUAL objects,
%   then Off is also an array of INDIVIDUAL objects; while if P is a matrix
%   of decision variables, then Off is also a matrix of decision variables,
%   i.e., the offsprings will not be evaluated. P is split into two subsets
%   P1 and P2 with the same size, and each object/row of P1 and P2 is used
%   to generate TWO offsprings. Different operators are used for real,
%   binary, and permutation based encodings, respectively.
%
%   Off = GA(P,{proC,disC,proM,disM}) specifies the parameters of
%   operators, where proC is the probabilities of doing crossover, disC is
%   the distribution index of simulated binary crossover, proM is the
%   expectation of number of bits doing mutation, and disM is the
%   distribution index of polynomial mutation.
%
%   Example:
%       Off = GA(Parent)
%       Off = GA(Parent.decs,{1,20,1,20})
%
%   See also GAhalf

%------------------------------- Reference --------------------------------
% [1] K. Deb, K. Sindhya, and T. Okabe, Self-adaptive simulated binary
% crossover for real-parameter optimization, Proceedings of the 9th Annual
% Conference on Genetic and Evolutionary Computation, 2007, 1187-1194.
% [2] K. Deb and M. Goyal, A combined genetic adaptive search (GeneAS) for
% engineering design, Computer Science and informatics, 1996, 26: 30-45.
% [3] L. Davis, Applying adaptive algorithms to epistatic domains,
% Proceedings of the International Joint Conference on Artificial
% Intelligence, 1985, 162-164.
% [4] D. B. Fogel, An evolutionary approach to the traveling salesman
% problem, Biological Cybernetics, 1988, 60(2): 139-144.
%------------------------------- Copyright --------------------------------
% Copyright (c) 2018-2019 BIMK Group. You are free to use the PlatEMO for
% research purposes. All publications which use this platform or any code
% in the platform should acknowledge the use of "PlatEMO" and reference "Ye
% Tian, Ran Cheng, Xingyi Zhang, and Yaochu Jin, PlatEMO: A MATLAB platform
% for evolutionary multi-objective optimization [educational forum], IEEE
% Computational Intelligence Magazine, 2017, 12(4): 73-87".
%--------------------------------------------------------------------------

    %% Parameter setting
    if nargin > 1
        [proC,disC,proM,disM] = deal(Parameter{:});
    else
        [proC,disC,proM,disM] = deal(1,20,1,20);
    end
    if isa(Parent(1),'INDIVIDUAL')
        calObj = true;
        Parent = Parent.decs;
    else
        calObj = false;
    end
    Parent1 = Parent(1:floor(end/2),:);
    Parent2 = Parent(floor(end/2)+1:floor(end/2)*2,:);
    [N,D]   = size(Parent1);
 
    switch encoding
        case 'binary'
            %% Genetic operators for binary encoding
            % One point crossover
            k = repmat(1:D,N,1) > repmat(randi(D,N,1),1,D);
            k(repmat(rand(N,1)>proC,1,D)) = false;
            Offspring1    = Parent1;
            Offspring2    = Parent2;
            Offspring1(k) = Parent2(k);
            Offspring2(k) = Parent1(k);
            Offspring     = [Offspring1;Offspring2];
            % Bitwise mutation
            Site = rand(2*N,D) < proM/D;
            Offspring(Site) = ~Offspring(Site);
        case 'permutation'
            %% Genetic operators for permutation based encoding
            % Order crossover
            Offspring = [Parent1;Parent2];
            k = randi(D,1,2*N);
            for i = 1 : N
                Offspring(i,k(i)+1:end)   = setdiff(Parent2(i,:),Parent1(i,1:k(i)),'stable');
                Offspring(i+N,k(i)+1:end) = setdiff(Parent1(i,:),Parent2(i,1:k(i)),'stable');
            end
            % Slight mutation
            k = randi(D,1,2*N);
            s = randi(D,1,2*N);
            for i = 1 : 2*N
                if s(i) < k(i)
                    Offspring(i,:) = Offspring(i,[1:s(i)-1,k(i),s(i):k(i)-1,k(i)+1:end]);
                elseif s(i) > k(i)
                    Offspring(i,:) = Offspring(i,[1:k(i)-1,k(i)+1:s(i)-1,k(i),s(i):end]);
                end
            end
        otherwise
            %% Genetic operators for real encoding
            % Simulated binary crossover
            beta = zeros(N,D);
            mu   = rand(N,D);
            beta(mu<=0.5) = (2*mu(mu<=0.5)).^(1/(disC+1));
            beta(mu>0.5)  = (2-2*mu(mu>0.5)).^(-1/(disC+1));
            beta = beta.*(-1).^randi([0,1],N,D);
            beta(rand(N,D)<0.5) = 1;
            beta(repmat(rand(N,1)>proC,1,D)) = 1;
%             test value
            beta=[1,-0.878870713,1,-0.920930292,1.005392461,-1.096583436,1.083902817,1,1,-1.011287183,0.992816033,1;
                    -1.110349385,-0.873485845,1,-0.962959982,-0.963243454,-1.063336868,0.886432583,0.951896223,1,1,1,1;
                    1,1,-1.04691477,1,0.951538268,1.007108557,-0.998326021,1.002432312,1,1,-1.063349371,-1.041392457;
                    1,1,1,0.900501563,1,1.033636659,0.903264628,0.971148024,1,-0.946106543,1,1]

            Offspring = [(Parent1+Parent2)/2+beta.*(Parent1-Parent2)/2
                         (Parent1+Parent2)/2-beta.*(Parent1-Parent2)/2];
            % Polynomial mutation
            Lower = repmat(lower,2*N,1);
            Upper = repmat(upper,2*N,1);
            Site  = rand(2*N,D) < proM/D;
%             test value
            Site=[1,1,0,0,0,0,0,1,0,0,0,0;
                    0,0,0,0,0,0,0,0,0,0,0,0;
                    0,0,0,0,0,0,0,0,0,0,0,0;
                    0,0,0,0,0,0,0,0,0,0,0,0;
                    0,0,0,0,0,0,0,0,0,0,0,0;
                    0,0,0,0,0,0,0,0,0,1,0,1;
                    0,0,0,0,0,0,1,0,0,0,1,0;
                    1,0,0,0,0,0,0,0,0,0,0,0]

            mu    = rand(2*N,D);
%             test value
            mu=[0.624839298,0.369995778,0.10970764,0.219856621,0.533680366,0.931944542,0.284911832,0.209206592,0.325568356,0.644241396,0.962398359,0.826637025;
0.016991584,0.197278359,0.749724825,0.562153788,0.564333458,0.109185912,0.86834697,0.320817053,0.183212354,0.496115902,0.942216114,0.403104491;
0.184094407,0.630484457,0.033729,0.566771511,0.302863316,0.976188427,0.964296963,0.542763046,0.816640317,0.456764777,0.153972744,0.564214618;
0.038243251,0.603972472,0.609786042,0.895609427,0.626072884,0.992929495,0.472212724,0.000528076,0.780945301,0.821961692,0.843344089,0.058997741;
0.709967537,0.462649651,0.012472086,0.048386347,0.960229536,0.639894086,0.660292141,0.796967948,0.866355124,0.428343185,0.236795931,0.228880588;
0.526860769,0.292149839,0.259385915,0.597298454,0.790664812,0.287689763,0.519944039,0.260642325,0.81215641,0.091940903,0.896178825,0.002919548;
0.575588584,0.451375377,0.416451222,0.41813774,0.890301028,0.342187696,0.71041813,0.528475246,0.546380853,0.245318474,0.621473305,0.62492191;
0.93013724,0.992170714,0.091569941,0.372750828,0.383556775,0.0230959,0.073962309,0.715610665,0.079024727,0.610889619,0.194665362,0.825140308]

            temp  = Site & mu<=0.5;
            Offspring       = min(max(Offspring,Lower),Upper);
            Offspring(temp) = Offspring(temp)+(Upper(temp)-Lower(temp)).*((2.*mu(temp)+(1-2.*mu(temp)).*...
                              (1-(Offspring(temp)-Lower(temp))./(Upper(temp)-Lower(temp))).^(disM+1)).^(1/(disM+1))-1);
            temp = Site & mu>0.5; 
            Offspring(temp) = Offspring(temp)+(Upper(temp)-Lower(temp)).*(1-(2.*(1-mu(temp))+2.*(mu(temp)-0.5).*...
                              (1-(Upper(temp)-Offspring(temp))./(Upper(temp)-Lower(temp))).^(disM+1)).^(1/(disM+1)));
    end
    if calObj
        Offspring = INDIVIDUAL(Offspring);
    end
end